### ISSUE TITLE
Docker version

### ISSUE THREAD

**Issue by quick-tutoriel** [manuelernestog/weektodo#160]
Hello,

I like your application because of its simplicity and convenience. Do you plan a docker version that could be self-hosted on a server?

Thank you in advance for your answer.

**Comment by manuelernestog** [comment]
Hi @quick-tutoriel thanks for writing. Well for now, the applicationworks on the client side, so there is no server. The idea is to implement a synchronization system with the clouds so that the user, for example, if he wants to set up his own nextcloud server, can do so and synchronize with it or with another service. Perhaps in the future, the development of a server will be considered to be able to provide other characteristics to the application.

**Comment by Shahin-rmz** [comment]
> Hi @quick-tutoriel thanks for writing. Well for now, the applicationworks on the client side, so there is no server. The idea is to implement a synchronization system with the clouds so that the user, for example, if he wants to set up his own nextcloud server, can do so and synchronize with it or with another service. Perhaps in the future, the development of a server will be considered to be able to provide other characteristics to the application.

I second that. If you like, I can help make Python FastAPI server for the app.
it will be awesome if we can have our tasks on mobile and laptop synced, even better if synced with nextcloud tasks.

**Comment by manuelernestog** [comment]
Hi @Shahin-rmz. Well right now the roadmap to get to the synchronization between devices is a bit long.

First I have to refactor the way the weektodo data model is implemented right now to then think about synchronization.

My intention is when this is ready to be able to create a mechanism to synchronize the data that can work as a service for those who don't know about servers or self-hosted for those who want it, but again to get here there is work ahead.
